/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Form: typeof import('./components/Form.vue')['default']
    FormGroup: typeof import('./components/FormGroup.vue')['default']
    FormInput: typeof import('./components/FormInput.vue')['default']
    FormSelect: typeof import('./components/FormSelect.vue')['default']
  }
}
