name: Comment PR

inputs:
  body:
    type: string
    required: true
  is_file:
    type: boolean
    default: false
  update_comment:
    type: boolean
    default: true

runs:
  using: 'composite'
  steps:
    - name: echo 1
      run: echo ${{ inputs.body }}
      shell: bash

    - name: echo 2
      run: echo ${{ inputs.is_file }}
      shell: bash

    - name: echo 3
      run: echo ${{ inputs.update_comment }}
      shell: bash

    - name: echo 4
      run: echo ${{ inputs.is_file == 'true' }}
      shell: bash

    - name: echo 5
      run: echo ${{ inputs.is_file == 'false' }}
      shell: bash

    - name: Try update comment
      if: inputs.update_comment == true
      id: update
      continue-on-error: true
      shell: bash
      run: |
        gh pr comment ${{github.event.number}} \
          --repo ${{github.repository}} \
          ${{ inputs.is_file == 'true' && '--body-file' || '--body' }} '${{ inputs.body }}' \
          --edit-last
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Add new comment
      if: steps.update.outcome != 'success' || inputs.update_comment == false
      shell: bash
      run: |
        gh pr comment ${{github.event.number}} \
          --repo ${{github.repository}} \
          ${{ inputs.is_file == 'true' && '--body-file' || '--body' }} '${{ inputs.body }}'
      env:
        GH_TOKEN: ${{ github.token }}
