name: Comment PR

on:
  workflow_call:
    inputs:
      body:
        required: true
        type: string
      is_file:
        type: boolean
        default: false

runs:
  using: 'composite'
  steps:
    - name: Try update comment
      id: update
      continue-on-error: true
      shell: bash
      run: |
        gh pr comment ${{github.event.number}} \
          --repo ${{github.repository}} \
          ${{ inputs.is_file && '--body-file' || '--body' }} '${{ inputs.body }}' \
          --edit-last
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Add new comment
      if: steps.update.outcome != 'success'
      shell: bash
      run: |
        gh pr comment ${{github.event.number}} \
          --repo ${{github.repository}} \
          ${{ inputs.is_file && '--body-file' || '--body' }} '${{ inputs.body }}'
      env:
        GH_TOKEN: ${{ github.token }}
