name: Build

on:
  - workflow_call

jobs:
  build:
    name: Docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Restore build cache
        uses: actions/download-artifact@v4
        with:
          name: lib-build
          path: packages/lib/dist

      - name: Install dependencies
        run: pnpm --filter docs install

      - name: Build docs
        run: pnpm --filter docs build

      - name: Cache build
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: packages/docs/.vitepress
