name: Build

on:
  - workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter @vuetils/vue-useform install

      - name: Build lib
        run: pnpm --filter @vuetils/vue-useform build

      - name: Cache dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: packages/lib/dist
