name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build_lib.yml

  format:
    name: Format
    uses: ./.github/workflows/format.yml

  test:
    name: Test
    needs:
      - build
      - format
    uses: ./.github/workflows/test_lib.yml

  release:
    if: github.event_name == 'push'
    name: Release
    needs:
      - test
    uses: ./.github/workflows/release_lib.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy_docs:
    if: github.event_name == 'push'
    name: Deploy
    needs:
      - test
    uses: ./.github/workflows/deploy_docs.yml
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
