name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  format:
    name: Format
    uses: ./.github/workflows/format.yml

  test:
    name: Test
    needs:
      - build
    uses: ./.github/workflows/test.yml

  release:
    if: github.event_name == 'push'
    name: Release
    needs:
      - test
      - format
    uses: ./.github/workflows/release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
