name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: test
    uses: ./.github/workflows/release.yml
    secrets:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
