name: CI

on:
  push:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml
