name: CI

on:
  push:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  format:
    name: Format
    uses: ./.github/workflows/format.yml

  test:
    name: Test
    needs:
      - build
      - format
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: test
    uses: ./.github/workflows/release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
