name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  comment:
    if: github.event_name == 'pull_request'
    steps:
      name: Test Comment
      run: |
        gh api \
          --method POST \
          -H 'Accept: application/vnd.github+json' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          /repos/${{github.repository_owner}}/${{github.repository}}/issues/${{github.event.number}}/comments \
          -f body='Me too'

  build_lib:
    name: Build
    uses: ./.github/workflows/build_lib.yml

  format:
    name: Format
    uses: ./.github/workflows/format.yml

  test:
    name: Test
    needs:
      - build_lib
      - format
    uses: ./.github/workflows/test_lib.yml

  release:
    if: github.event_name == 'push'
    name: Release lib
    needs:
      - test
    uses: ./.github/workflows/release_lib.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build_docs:
    name: Build
    needs:
      - build_lib
    uses: ./.github/workflows/build_docs.yml

  deploy_docs:
    # if: github.event_name == 'push'
    name: Deploy docs
    needs:
      - test
      - build_docs
    uses: ./.github/workflows/deploy_docs.yml
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
