name: Deploy

on:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true

jobs:
  deploy:
    name: ${{ startsWith(github.event.head_commit.message, 'chore(release)') && 'Production' || 'Canary'}}

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Restore docs-build cache
        uses: actions/download-artifact@v3
        with:
          name: docs-build
          path: packages/docs/.vitepress

      - name: Install dependencies
        run: pnpm --filter docs install

      - name: Deploy docs canary
        run: pnpm --filter docs deploy:dev | tail -n 1 > preview_url.txt
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Add preview url comment
        if: github.event_name == 'pull_request'
        uses: ./.github/workflows/pr_comment.yml
        with:
          body: preview_url.txt
          is_file: true
          update_comment: true

      - name: Add preview URL to PR
        uses: mshick/add-pr-comment@v2
        with:
          message-path: preview_url.txt
