name: Deploy

on:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true

jobs:
  deploy:
    name: Docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter @vuetils/vue-useform install

      - name: Restore dist cache
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: packages/lib/dist

      - name: Install dependencies
        run: pnpm --filter docs install

      - name: Build docs
        run: pnpm --filter docs build

      - name: Deploy docs
        run: pnpm --filter docs deploy:prod
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
