name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    defaults:
      run:
        working-directory: packages/lib

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - run: pnpm --filter @yannicel/vue-useform install

      - run: pnpm run build
