name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    defaults:
      run:
        working-directory: frontend

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.0.0-alpha.0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - run: pnpm --filter @yannicel/vue-useform install

      - run: pnpm run build
