name: Comment

on:
  workflow_call:
    inputs:
      body:
        required: true
        type: string
      is_file:
        type: boolean
        default: false
      update_comment:
        type: boolean
        default: false

jobs:
  comment:
    name: PR

    runs-on: ubuntu-latest

    steps:
      - name: Add or update comment
        run: |
          gh pr comment ${{github.event.number}} \
            --repo ${{github.repository}} \
            ${{ inputs.is_file && '--body-file' || '--body' }} '${{ inputs.body }}' \
            ${{ inputs.update_comment && '--edit-last' || '' }}
        env:
          GH_TOKEN: ${{ github.token }}
