name: Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
      id-token: write # to create releae with provenance

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --filter @vuetils/vue-useform install

      - name: Build lib
        run: pnpm --filter @vuetils/vue-useform build

      - name: Set npm token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: echo
        run: echo ${{ github.ref_name }} ${{ github.ref }}

      - name: Publish release
        run: pnpm publish --filter @vuetils/vue-useform
        env:
          NPM_CONFIG_PROVENANCE: true
